import type { BetterDirection, MetricDefinitionType, MetricUnit } from './types';

type MetricDefinition = {
	id: string;
	createdAt: string;
	updatedAt: string;
	orgId: string | null;
	isPublic: boolean;
	name: string;
	description: string;
	type: MetricDefinitionType;
	category: string;
	betterDirection: BetterDirection;
	formula: string | null;
	sourceMetricDefinitionIds: string[] | null;
	unit: MetricUnit;
	roundingPrecision: number;
	meta: Record<string, unknown>;
};

type PerformanceAssessmentTemplateItem = {
	metricDefinitionId: string;
	scored: boolean;
};

type PerformanceAssessmentTemplate = {
	id: string;
	createdAt: string;
	updatedAt: string;
	orgId: string;
	name: string;
	description: string | null;
	items: PerformanceAssessmentTemplateItem[];
	meta?: Record<string, unknown>;
};

type ReferenceBand = {
	mean: number;
	std: number;
};

type ReferenceTable = Record<string, Record<string, ReferenceBand | null>>;

const now = '2025-01-01T00:00:00.000Z';

export const metricDefinitions: MetricDefinition[] = [
	{
		id: '3s004Lb8UM9Tiag3kQNR',
		createdAt: now,
		updatedAt: now,
		orgId: null,
		isPublic: true,
		name: '身長',
		description: '',
		type: 'raw',
		category: 'BODY',
		betterDirection: 'HIGHER_IS_BETTER',
		formula: null,
		sourceMetricDefinitionIds: null,
		unit: 'CENTIMETER',
		roundingPrecision: 1,
		meta: {},
	},
	{
		id: '5iu1YWxuZFt6X2Stg0iy',
		createdAt: now,
		updatedAt: now,
		orgId: null,
		isPublic: true,
		name: '両足５段跳び',
		description: '',
		type: 'raw',
		category: 'POWER',
		betterDirection: 'HIGHER_IS_BETTER',
		formula: null,
		sourceMetricDefinitionIds: null,
		unit: 'METER',
		roundingPrecision: 2,
		meta: {},
	},
	{
		id: '9Ubx6BwRXrl4Fqc60BEQ',
		createdAt: now,
		updatedAt: now,
		orgId: null,
		isPublic: true,
		name: '3 HOP 左',
		description: '',
		type: 'raw',
		category: 'POWER',
		betterDirection: 'HIGHER_IS_BETTER',
		formula: null,
		sourceMetricDefinitionIds: null,
		unit: 'METER',
		roundingPrecision: 2,
		meta: {},
	},
	{
		id: 'FEEunCRt96GG5wXvoDWm',
		createdAt: now,
		updatedAt: now,
		orgId: null,
		isPublic: true,
		name: 'Pro Agility 右',
		description: '',
		type: 'raw',
		category: 'AGILITY',
		betterDirection: 'LOWER_IS_BETTER',
		formula: null,
		sourceMetricDefinitionIds: null,
		unit: 'SECOND',
		roundingPrecision: 2,
		meta: {},
	},
	{
		id: 'HWtqdoyh1WIjpJIGtHbM',
		createdAt: now,
		updatedAt: now,
		orgId: null,
		isPublic: true,
		name: 'Pro Agility 左右差(%)',
		description: '',
		type: 'derived',
		category: 'AGILITY',
		betterDirection: 'LOWER_IS_BETTER',
		formula:
			'=ROUND(ABS($FEEunCRt96GG5wXvoDWm-$UiJ8YCBfUdI9OPnknlU4)/MIN($FEEunCRt96GG5wXvoDWm,$UiJ8YCBfUdI9OPnknlU4), 6)',
		sourceMetricDefinitionIds: ['FEEunCRt96GG5wXvoDWm', 'UiJ8YCBfUdI9OPnknlU4'],
		unit: 'PERCENT',
		roundingPrecision: 2,
		meta: {},
	},
	{
		id: 'Hi5CitOIe4MLS2uF3dqc',
		createdAt: now,
		updatedAt: now,
		orgId: null,
		isPublic: true,
		name: '3 HOP 右',
		description: '',
		type: 'raw',
		category: 'POWER',
		betterDirection: 'HIGHER_IS_BETTER',
		formula: null,
		sourceMetricDefinitionIds: null,
		unit: 'METER',
		roundingPrecision: 2,
		meta: {},
	},
	{
		id: 'JyCFHqA5HAOBPcqCOwCv',
		createdAt: now,
		updatedAt: now,
		orgId: null,
		isPublic: true,
		name: '体重',
		description: '',
		type: 'raw',
		category: 'BODY',
		betterDirection: 'HIGHER_IS_BETTER',
		formula: null,
		sourceMetricDefinitionIds: null,
		unit: 'KILOGRAM',
		roundingPrecision: 1,
		meta: {},
	},
	{
		id: 'UiJ8YCBfUdI9OPnknlU4',
		createdAt: now,
		updatedAt: now,
		orgId: null,
		isPublic: true,
		name: 'Pro Agility 左',
		description: '',
		type: 'raw',
		category: 'AGILITY',
		betterDirection: 'LOWER_IS_BETTER',
		formula: null,
		sourceMetricDefinitionIds: null,
		unit: 'SECOND',
		roundingPrecision: 2,
		meta: {},
	},
	{
		id: 'V1AdIWTGwvVa2RYmZLsC',
		createdAt: now,
		updatedAt: now,
		orgId: null,
		isPublic: true,
		name: 'BMI',
		description: '',
		type: 'derived',
		category: 'BODY',
		betterDirection: 'HIGHER_IS_BETTER',
		formula: '=ROUND( $JyCFHqA5HAOBPcqCOwCv / POWER($3s004Lb8UM9Tiag3kQNR / 100, 2), 6)',
		sourceMetricDefinitionIds: ['3s004Lb8UM9Tiag3kQNR', 'JyCFHqA5HAOBPcqCOwCv'],
		unit: 'UNITLESS',
		roundingPrecision: 1,
		meta: {},
	},
	{
		id: 'i3tQbxmRVijkzlXngPan',
		createdAt: now,
		updatedAt: now,
		orgId: null,
		isPublic: true,
		name: '3 HOP 左右差(%)',
		description: '',
		type: 'derived',
		category: 'POWER',
		betterDirection: 'LOWER_IS_BETTER',
		formula:
			'=ROUND(ABS( $9Ubx6BwRXrl4Fqc60BEQ - $Hi5CitOIe4MLS2uF3dqc ) / MIN( $9Ubx6BwRXrl4Fqc60BEQ , $Hi5CitOIe4MLS2uF3dqc ), 6)',
		sourceMetricDefinitionIds: ['9Ubx6BwRXrl4Fqc60BEQ', 'Hi5CitOIe4MLS2uF3dqc'],
		unit: 'PERCENT',
		roundingPrecision: 2,
		meta: {},
	},
	{
		id: 'lMaeLRMQfMa1WKbOyly7',
		createdAt: now,
		updatedAt: now,
		orgId: null,
		isPublic: true,
		name: '立ち幅跳び',
		description: '',
		type: 'raw',
		category: 'POWER',
		betterDirection: 'HIGHER_IS_BETTER',
		formula: null,
		sourceMetricDefinitionIds: null,
		unit: 'METER',
		roundingPrecision: 2,
		meta: {},
	},
	{
		id: 'ojpzLOSCTMZf6s4SvRja',
		createdAt: now,
		updatedAt: now,
		orgId: null,
		isPublic: true,
		name: '3 HOP 平均',
		description: '',
		type: 'derived',
		category: 'POWER',
		betterDirection: 'HIGHER_IS_BETTER',
		formula: '=ROUND(AVERAGE($9Ubx6BwRXrl4Fqc60BEQ,$Hi5CitOIe4MLS2uF3dqc), 6)',
		sourceMetricDefinitionIds: ['9Ubx6BwRXrl4Fqc60BEQ', 'Hi5CitOIe4MLS2uF3dqc'],
		unit: 'METER',
		roundingPrecision: 2,
		meta: {},
	},
	{
		id: 'sgUyE2xgSX4d5YLDVFdO',
		createdAt: now,
		updatedAt: now,
		orgId: null,
		isPublic: true,
		name: '20M スプリント',
		description: '',
		type: 'raw',
		category: 'SPEED',
		betterDirection: 'LOWER_IS_BETTER',
		formula: null,
		sourceMetricDefinitionIds: null,
		unit: 'SECOND',
		roundingPrecision: 2,
		meta: {},
	},
	{
		id: 'u5Wdg1MlL88rYKbPQW3o',
		createdAt: now,
		updatedAt: now,
		orgId: null,
		isPublic: true,
		name: 'Pro Agility 平均',
		description: '',
		type: 'derived',
		category: 'AGILITY',
		betterDirection: 'LOWER_IS_BETTER',
		formula: '=ROUND(AVERAGE($FEEunCRt96GG5wXvoDWm,$UiJ8YCBfUdI9OPnknlU4), 6)',
		sourceMetricDefinitionIds: ['FEEunCRt96GG5wXvoDWm', 'UiJ8YCBfUdI9OPnknlU4'],
		unit: 'SECOND',
		roundingPrecision: 2,
		meta: {},
	},
	{
		id: 'uaaLUh0KRykPkWA3Dhcd',
		createdAt: now,
		updatedAt: now,
		orgId: null,
		isPublic: true,
		name: '30M スプリント',
		description: '',
		type: 'raw',
		category: 'SPEED',
		betterDirection: 'LOWER_IS_BETTER',
		formula: null,
		sourceMetricDefinitionIds: null,
		unit: 'SECOND',
		roundingPrecision: 2,
		meta: {},
	},
	{
		id: 'uhQDnmvGVOGPgEYAxJh0',
		createdAt: now,
		updatedAt: now,
		orgId: null,
		isPublic: true,
		name: '10M スプリント',
		description: '',
		type: 'raw',
		category: 'SPEED',
		betterDirection: 'LOWER_IS_BETTER',
		formula: null,
		sourceMetricDefinitionIds: null,
		unit: 'SECOND',
		roundingPrecision: 2,
		meta: {},
	},
	{
		id: 'y7h8I9Mkl1ppg5ZmRpUb',
		createdAt: now,
		updatedAt: now,
		orgId: null,
		isPublic: true,
		name: 'YoYo',
		description: '',
		type: 'raw',
		category: 'ENDURANCE',
		betterDirection: 'HIGHER_IS_BETTER',
		formula: null,
		sourceMetricDefinitionIds: null,
		unit: 'COUNT',
		roundingPrecision: 0,
		meta: {},
	},
	{
		id: '0xbH1n71xspfVRddG92Q',
		createdAt: now,
		updatedAt: now,
		orgId: '2a9dWrDixJ56ysNOgAtR',
		isPublic: false,
		name: 'Zone 1 距離',
		description: 'Fitogether Zone 1 距離',
		type: 'raw',
		category: 'TRAINING',
		betterDirection: 'HIGHER_IS_BETTER',
		formula: null,
		sourceMetricDefinitionIds: null,
		unit: 'METER',
		roundingPrecision: 0,
		meta: {},
	},
	{
		id: '4Pf9FuE2agjFASX1acXF',
		createdAt: now,
		updatedAt: now,
		orgId: '2a9dWrDixJ56ysNOgAtR',
		isPublic: false,
		name: 'Accel Zone 4 回数',
		description: 'Fitogether Accel Zone 4 回数',
		type: 'raw',
		category: 'TRAINING',
		betterDirection: 'HIGHER_IS_BETTER',
		formula: null,
		sourceMetricDefinitionIds: null,
		unit: 'COUNT',
		roundingPrecision: 0,
		meta: {},
	},
	{
		id: 'D7aoPeenTMYu3CxfR6v7',
		createdAt: now,
		updatedAt: now,
		orgId: '2a9dWrDixJ56ysNOgAtR',
		isPublic: false,
		name: '減速合計回数',
		description: 'Fitogether 減速合計回数',
		type: 'raw',
		category: 'TRAINING',
		betterDirection: 'HIGHER_IS_BETTER',
		formula: null,
		sourceMetricDefinitionIds: null,
		unit: 'COUNT',
		roundingPrecision: 0,
		meta: {},
	},
	{
		id: 'FSmTTs8BG3fq608Zcy4F',
		createdAt: now,
		updatedAt: now,
		orgId: '2a9dWrDixJ56ysNOgAtR',
		isPublic: false,
		name: 'Decel Zone 4 回数',
		description: 'Fitogether Decel Zone 4 回数',
		type: 'raw',
		category: 'TRAINING',
		betterDirection: 'HIGHER_IS_BETTER',
		formula: null,
		sourceMetricDefinitionIds: null,
		unit: 'COUNT',
		roundingPrecision: 0,
		meta: {},
	},
	{
		id: 'FSw4meWwvmxkcr4G0KvX',
		createdAt: now,
		updatedAt: now,
		orgId: '2a9dWrDixJ56ysNOgAtR',
		isPublic: false,
		name: 'TRスコア消費',
		description: 'Fitogether TRスコア消費',
		type: 'raw',
		category: 'TRAINING',
		betterDirection: 'HIGHER_IS_BETTER',
		formula: null,
		sourceMetricDefinitionIds: null,
		unit: 'UNITLESS',
		roundingPrecision: 0,
		meta: {},
	},
	{
		id: 'I7i8bessV96ciVnFw5IB',
		createdAt: now,
		updatedAt: now,
		orgId: '2a9dWrDixJ56ysNOgAtR',
		isPublic: false,
		name: '走行距離/分',
		description: 'Fitogether 走行距離/分',
		type: 'raw',
		category: 'TRAINING',
		betterDirection: 'HIGHER_IS_BETTER',
		formula: null,
		sourceMetricDefinitionIds: null,
		unit: 'METER',
		roundingPrecision: 0,
		meta: {},
	},
	{
		id: 'KkLOxGTCHY2uVOMjLtQE',
		createdAt: now,
		updatedAt: now,
		orgId: '2a9dWrDixJ56ysNOgAtR',
		isPublic: false,
		name: 'トレーニング時間',
		description: 'Fitogether トレーニング時間です。',
		type: 'raw',
		category: 'TRAINING',
		betterDirection: 'HIGHER_IS_BETTER',
		formula: null,
		sourceMetricDefinitionIds: null,
		unit: 'MINUTE',
		roundingPrecision: 0,
		meta: {},
	},
	{
		id: 'Kn39OEkrpQCMQAtMQb5J',
		createdAt: now,
		updatedAt: now,
		orgId: '2a9dWrDixJ56ysNOgAtR',
		isPublic: false,
		name: '高強度距離',
		description: 'Fitogether トレーニング高強度',
		type: 'raw',
		category: 'TRAINING',
		betterDirection: 'HIGHER_IS_BETTER',
		formula: null,
		sourceMetricDefinitionIds: null,
		unit: 'METER',
		roundingPrecision: 0,
		meta: {},
	},
	{
		id: 'P6Zu5epLjDOaDQq20Stx',
		createdAt: now,
		updatedAt: now,
		orgId: '2a9dWrDixJ56ysNOgAtR',
		isPublic: false,
		name: '走行距離',
		description: 'Fitogether トレーニング走行距離',
		type: 'raw',
		category: 'TRAINING',
		betterDirection: 'HIGHER_IS_BETTER',
		formula: null,
		sourceMetricDefinitionIds: null,
		unit: 'METER',
		roundingPrecision: 0,
		meta: {},
	},
	{
		id: 'Q4dPRJ2eqeNR0Bg4DI3E',
		createdAt: now,
		updatedAt: now,
		orgId: '2a9dWrDixJ56ysNOgAtR',
		isPublic: false,
		name: '最大速度',
		description: 'Fitogether 最大速度',
		type: 'raw',
		category: 'TRAINING',
		betterDirection: 'HIGHER_IS_BETTER',
		formula: null,
		sourceMetricDefinitionIds: null,
		unit: 'KMPH',
		roundingPrecision: 1,
		meta: {},
	},
	{
		id: 'RObqK0yOMf4NXhiWig6p',
		createdAt: now,
		updatedAt: now,
		orgId: '2a9dWrDixJ56ysNOgAtR',
		isPublic: false,
		name: '高強度割合',
		description: 'Fitogether トレーニング高強度割合',
		type: 'raw',
		category: 'TRAINING',
		betterDirection: 'HIGHER_IS_BETTER',
		formula: null,
		sourceMetricDefinitionIds: null,
		unit: 'PERCENT',
		roundingPrecision: 0,
		meta: {},
	},
	{
		id: 'XLp9zGyDi0PgkNHn61ln',
		createdAt: now,
		updatedAt: now,
		orgId: '2a9dWrDixJ56ysNOgAtR',
		isPublic: false,
		name: 'Exp Accel回数',
		description: 'Fitogether Exp Accel回数',
		type: 'raw',
		category: 'TRAINING',
		betterDirection: 'HIGHER_IS_BETTER',
		formula: null,
		sourceMetricDefinitionIds: null,
		unit: 'COUNT',
		roundingPrecision: 0,
		meta: {},
	},
	{
		id: 'XYpyu5CZTDZmMY9DbfNG',
		createdAt: now,
		updatedAt: now,
		orgId: '2a9dWrDixJ56ysNOgAtR',
		isPublic: false,
		name: '加速合計回数',
		description: 'Fitogether 加速合計回数',
		type: 'raw',
		category: 'TRAINING',
		betterDirection: 'HIGHER_IS_BETTER',
		formula: null,
		sourceMetricDefinitionIds: null,
		unit: 'COUNT',
		roundingPrecision: 0,
		meta: {},
	},
	{
		id: 'YR3ZEOZLTLwJk23XKVpj',
		createdAt: now,
		updatedAt: now,
		orgId: '2a9dWrDixJ56ysNOgAtR',
		isPublic: false,
		name: 'Accel Zone 6 回数',
		description: 'Fitogether Accel Zone 6 回数',
		type: 'raw',
		category: 'TRAINING',
		betterDirection: 'HIGHER_IS_BETTER',
		formula: null,
		sourceMetricDefinitionIds: null,
		unit: 'COUNT',
		roundingPrecision: 0,
		meta: {},
	},
	{
		id: 'ZfqkRYcNfvwYioquCx5h',
		createdAt: now,
		updatedAt: now,
		orgId: '2a9dWrDixJ56ysNOgAtR',
		isPublic: false,
		name: 'スプリント回数',
		description: 'Fitogether スプリント回数',
		type: 'raw',
		category: 'TRAINING',
		betterDirection: 'HIGHER_IS_BETTER',
		formula: null,
		sourceMetricDefinitionIds: null,
		unit: 'COUNT',
		roundingPrecision: 0,
		meta: {},
	},
	{
		id: 'b3DroV7arY2KLRUJpdtq',
		createdAt: now,
		updatedAt: now,
		orgId: '2a9dWrDixJ56ysNOgAtR',
		isPublic: false,
		name: 'トレーニングスコア消費',
		description: 'Fitogether トレーニングスコア消費',
		type: 'raw',
		category: 'TRAINING',
		betterDirection: 'HIGHER_IS_BETTER',
		formula: null,
		sourceMetricDefinitionIds: null,
		unit: 'UNITLESS',
		roundingPrecision: 0,
		meta: {},
	},
	{
		id: 'g60b48TuNLrtstb0dy65',
		createdAt: now,
		updatedAt: now,
		orgId: '2a9dWrDixJ56ysNOgAtR',
		isPublic: false,
		name: 'Decel Zone 5 回数',
		description: 'Fitogether Decel Zone 5 回数',
		type: 'raw',
		category: 'TRAINING',
		betterDirection: 'HIGHER_IS_BETTER',
		formula: null,
		sourceMetricDefinitionIds: null,
		unit: 'COUNT',
		roundingPrecision: 0,
		meta: {},
	},
	{
		id: 'j6u2oo2CjbSngFLioS2Q',
		createdAt: now,
		updatedAt: now,
		orgId: '2a9dWrDixJ56ysNOgAtR',
		isPublic: false,
		name: 'Zone 3 距離',
		description: 'Fitogether Zone 3 距離',
		type: 'raw',
		category: 'TRAINING',
		betterDirection: 'HIGHER_IS_BETTER',
		formula: null,
		sourceMetricDefinitionIds: null,
		unit: 'METER',
		roundingPrecision: 0,
		meta: {},
	},
	{
		id: 'kCZxKxfA9MfWVgBmdTbo',
		createdAt: now,
		updatedAt: now,
		orgId: '2a9dWrDixJ56ysNOgAtR',
		isPublic: false,
		name: 'Accel Zone 5 回数',
		description: 'Fitogether Accel Zone 5 回数',
		type: 'raw',
		category: 'TRAINING',
		betterDirection: 'HIGHER_IS_BETTER',
		formula: null,
		sourceMetricDefinitionIds: null,
		unit: 'COUNT',
		roundingPrecision: 0,
		meta: {},
	},
	{
		id: 'mPoLSRIgbc1IwC3fPsP9',
		createdAt: now,
		updatedAt: now,
		orgId: '2a9dWrDixJ56ysNOgAtR',
		isPublic: false,
		name: 'Decel Zone 6 回数',
		description: 'Fitogether Decel Zone 6 回数',
		type: 'raw',
		category: 'TRAINING',
		betterDirection: 'HIGHER_IS_BETTER',
		formula: null,
		sourceMetricDefinitionIds: null,
		unit: 'COUNT',
		roundingPrecision: 0,
		meta: {},
	},
	{
		id: 'mVykVPzBokSZ0l4C7YhJ',
		createdAt: now,
		updatedAt: now,
		orgId: '2a9dWrDixJ56ysNOgAtR',
		isPublic: false,
		name: 'スプリント距離',
		description: 'Fitogether スプリント距離',
		type: 'raw',
		category: 'TRAINING',
		betterDirection: 'HIGHER_IS_BETTER',
		formula: null,
		sourceMetricDefinitionIds: null,
		unit: 'METER',
		roundingPrecision: 0,
		meta: {},
	},
	{
		id: 'nulFBwmrHVrA20HPtNrp',
		createdAt: now,
		updatedAt: now,
		orgId: '2a9dWrDixJ56ysNOgAtR',
		isPublic: false,
		name: 'Zone 5 距離',
		description: 'Fitogether Zone 5 距離',
		type: 'raw',
		category: 'TRAINING',
		betterDirection: 'HIGHER_IS_BETTER',
		formula: null,
		sourceMetricDefinitionIds: null,
		unit: 'METER',
		roundingPrecision: 0,
		meta: {},
	},
	{
		id: 'oKXeSMbv7zfV7WjTV4Wp',
		createdAt: now,
		updatedAt: now,
		orgId: '2a9dWrDixJ56ysNOgAtR',
		isPublic: false,
		name: 'Zone 4 距離',
		description: 'Fitogether Zone 4 距離',
		type: 'raw',
		category: 'TRAINING',
		betterDirection: 'HIGHER_IS_BETTER',
		formula: null,
		sourceMetricDefinitionIds: null,
		unit: 'METER',
		roundingPrecision: 0,
		meta: {},
	},
	{
		id: 'oOQMjHICxmf3nLwvDitk',
		createdAt: now,
		updatedAt: now,
		orgId: '2a9dWrDixJ56ysNOgAtR',
		isPublic: false,
		name: 'ウォーキング割合',
		description: 'Fitogether ウォーキング割合',
		type: 'raw',
		category: 'TRAINING',
		betterDirection: 'HIGHER_IS_BETTER',
		formula: null,
		sourceMetricDefinitionIds: null,
		unit: 'PERCENT',
		roundingPrecision: 0,
		meta: {},
	},
	{
		id: 'vMV5RRPagpuPxkoU8F2T',
		createdAt: now,
		updatedAt: now,
		orgId: '2a9dWrDixJ56ysNOgAtR',
		isPublic: false,
		name: 'Exp Decell 回数',
		description: 'Fitogether Exp Decell 回数',
		type: 'raw',
		category: 'TRAINING',
		betterDirection: 'HIGHER_IS_BETTER',
		formula: null,
		sourceMetricDefinitionIds: null,
		unit: 'COUNT',
		roundingPrecision: 0,
		meta: {},
	},
	{
		id: 'zNB0AN1gxSC4IvhgqmlF',
		createdAt: now,
		updatedAt: now,
		orgId: '2a9dWrDixJ56ysNOgAtR',
		isPublic: false,
		name: 'Zone 2 距離',
		description: 'Fitogether Zone 2 距離',
		type: 'raw',
		category: 'TRAINING',
		betterDirection: 'HIGHER_IS_BETTER',
		formula: null,
		sourceMetricDefinitionIds: null,
		unit: 'METER',
		roundingPrecision: 0,
		meta: {},
	},
];

export const performanceAssessmentTemplates: PerformanceAssessmentTemplate[] = [
	{
		id: 'lxIwgccLRJElDAkmHgEl',
		name: '藤野メソッド・フル',
		createdAt: '2025-04-20T05:20:09.732Z',
		updatedAt: '2025-04-20T05:20:09.732Z',
		orgId: 'default',
		description: '',
		items: [
			{ metricDefinitionId: '3s004Lb8UM9Tiag3kQNR', scored: false },
			{ metricDefinitionId: 'JyCFHqA5HAOBPcqCOwCv', scored: false },
			{ metricDefinitionId: 'V1AdIWTGwvVa2RYmZLsC', scored: false },
			{ metricDefinitionId: 'uhQDnmvGVOGPgEYAxJh0', scored: true },
			{ metricDefinitionId: 'sgUyE2xgSX4d5YLDVFdO', scored: true },
			{ metricDefinitionId: 'uaaLUh0KRykPkWA3Dhcd', scored: true },
			{ metricDefinitionId: 'FEEunCRt96GG5wXvoDWm', scored: false },
			{ metricDefinitionId: 'UiJ8YCBfUdI9OPnknlU4', scored: false },
			{ metricDefinitionId: 'HWtqdoyh1WIjpJIGtHbM', scored: false },
			{ metricDefinitionId: 'u5Wdg1MlL88rYKbPQW3o', scored: true },
			{ metricDefinitionId: 'Hi5CitOIe4MLS2uF3dqc', scored: false },
			{ metricDefinitionId: '9Ubx6BwRXrl4Fqc60BEQ', scored: false },
			{ metricDefinitionId: 'i3tQbxmRVijkzlXngPan', scored: false },
			{ metricDefinitionId: 'ojpzLOSCTMZf6s4SvRja', scored: true },
			{ metricDefinitionId: '5iu1YWxuZFt6X2Stg0iy', scored: true },
			{ metricDefinitionId: 'lMaeLRMQfMa1WKbOyly7', scored: true },
		],
	},
	{
		id: 'pBySImSxY3qMzLvbBMAW',
		name: '藤野メソッド・シンプル',
		createdAt: '2025-04-21T06:39:41.334Z',
		updatedAt: '2025-04-21T06:39:41.334Z',
		orgId: 'default',
		description: '',
		items: [
			{ metricDefinitionId: '3s004Lb8UM9Tiag3kQNR', scored: false },
			{ metricDefinitionId: 'JyCFHqA5HAOBPcqCOwCv', scored: false },
			{ metricDefinitionId: 'V1AdIWTGwvVa2RYmZLsC', scored: false },
			{ metricDefinitionId: 'uhQDnmvGVOGPgEYAxJh0', scored: true },
			{ metricDefinitionId: 'sgUyE2xgSX4d5YLDVFdO', scored: true },
			{ metricDefinitionId: 'uaaLUh0KRykPkWA3Dhcd', scored: true },
			{ metricDefinitionId: 'FEEunCRt96GG5wXvoDWm', scored: false },
			{ metricDefinitionId: 'UiJ8YCBfUdI9OPnknlU4', scored: false },
			{ metricDefinitionId: 'HWtqdoyh1WIjpJIGtHbM', scored: false },
			{ metricDefinitionId: 'u5Wdg1MlL88rYKbPQW3o', scored: true },
			{ metricDefinitionId: 'lMaeLRMQfMa1WKbOyly7', scored: true },
			{ metricDefinitionId: 'Hi5CitOIe4MLS2uF3dqc', scored: false },
			{ metricDefinitionId: '9Ubx6BwRXrl4Fqc60BEQ', scored: false },
			{ metricDefinitionId: 'i3tQbxmRVijkzlXngPan', scored: false },
			{ metricDefinitionId: 'ojpzLOSCTMZf6s4SvRja', scored: true },
		],
	},
];

export const referenceTable: ReferenceTable = {
	FEEunCRt96GG5wXvoDWm: {
		'U10-U12': null,
		'U16-U18': null,
	}, // Pro Agility 右
	UiJ8YCBfUdI9OPnknlU4: {
		'U10-U12': null,
		'U16-U18': null,
	}, // Pro Agility 左
	HWtqdoyh1WIjpJIGtHbM: {
		'U10-U12': null,
		'U16-U18': null,
	}, // Pro Agility 左右差(%)
	u5Wdg1MlL88rYKbPQW3o: {
		'U10-U12': { mean: 5.43, std: 0.21 },
		'U16-U18': { mean: 4.81, std: 0.13 },
	}, // Pro Agility 平均
	V1AdIWTGwvVa2RYmZLsC: {
		'U10-U12': null,
		'U16-U18': null,
	}, // BMI
	JyCFHqA5HAOBPcqCOwCv: {
		'U10-U12': null,
		'U16-U18': null,
	}, // 体重
	'3s004Lb8UM9Tiag3kQNR': {
		'U10-U12': null,
		'U16-U18': null,
	}, // 身長
	y7h8I9Mkl1ppg5ZmRpUb: {
		'U10-U12': null,
		'U16-U18': { mean: 24.7, std: 6.1 },
	}, // YoYo
	Hi5CitOIe4MLS2uF3dqc: {
		'U10-U12': null,
		'U16-U18': null,
	}, // 3 HOP 右
	'9Ubx6BwRXrl4Fqc60BEQ': {
		'U10-U12': null,
		'U16-U18': null,
	}, // 3 HOP 左
	i3tQbxmRVijkzlXngPan: {
		'U10-U12': null,
		'U16-U18': null,
	}, // 3 HOP 左右差(%)
	ojpzLOSCTMZf6s4SvRja: {
		'U10-U12': { mean: 4.42, std: 0.42 },
		'U16-U18': { mean: 6.44, std: 0.46 },
	}, // 3 HOP 平均
	'5iu1YWxuZFt6X2Stg0iy': {
		'U10-U12': { mean: 9, std: 0.79 },
		'U16-U18': { mean: 12.3, std: 0.73 },
	}, // 両足５段跳び
	lMaeLRMQfMa1WKbOyly7: {
		'U10-U12': { mean: 1.8285, std: 0.1603 },
		'U16-U18': { mean: 2.42, std: 0.1268 },
	}, // 立ち幅跳び
	uhQDnmvGVOGPgEYAxJh0: {
		'U10-U12': { mean: 2.1, std: 0.09 },
		'U16-U18': { mean: 1.77, std: 0.07 },
	}, // 10M スプリント
	sgUyE2xgSX4d5YLDVFdO: {
		'U10-U12': { mean: 3.63, std: 0.16 },
		'U16-U18': { mean: 3.03, std: 0.09 },
	}, // 20M スプリント
	uaaLUh0KRykPkWA3Dhcd: {
		'U10-U12': { mean: 5.12, std: 0.24 },
		'U16-U18': { mean: 4.22, std: 0.12 },
	}, // 30M スプリント
};

export const capabilitiesResponse = {
	version: 'v1',
	capabilities: {
		metricDefinitions: true,
		scoreProviders: true,
		performanceAssessmentTemplates: true,
	},
};
