import { METRIC_DEFINITION_IDS } from '$lib/constants/metric-definition-ids';

export const trainigMetricDefinitionIds = [
	METRIC_DEFINITION_IDS.durationMin,
	METRIC_DEFINITION_IDS.totalDistanceM,
	METRIC_DEFINITION_IDS.totalDistancePerMin,
	METRIC_DEFINITION_IDS.maxSpeedKMH,
	METRIC_DEFINITION_IDS.highIntensityM,
	METRIC_DEFINITION_IDS.highIntensityRate,
	METRIC_DEFINITION_IDS.noOfSprint,
	METRIC_DEFINITION_IDS.sprintDistanceM,
	METRIC_DEFINITION_IDS.speedZone1DistanceM,
	METRIC_DEFINITION_IDS.speedZone6DistanceM,
	METRIC_DEFINITION_IDS.speedZone7DistanceM,
	METRIC_DEFINITION_IDS.speedZone8DistanceM,
	METRIC_DEFINITION_IDS.speedZone9DistanceM,
	METRIC_DEFINITION_IDS.lowIntensityRate,
	METRIC_DEFINITION_IDS.accelerationZone5EntryCount,
	METRIC_DEFINITION_IDS.accelerationZone6EntryCount,
	METRIC_DEFINITION_IDS.accelerationCountTotal,
	METRIC_DEFINITION_IDS.noOfExpAcc,
	METRIC_DEFINITION_IDS.decelerationZone5EntryCount,
	METRIC_DEFINITION_IDS.decelerationZone6EntryCount,
	METRIC_DEFINITION_IDS.decelerationCountTotal,
	METRIC_DEFINITION_IDS.noOfExpDec,
	METRIC_DEFINITION_IDS.noOfHSR,
	METRIC_DEFINITION_IDS.hsrDistanceM,
	METRIC_DEFINITION_IDS.trainingScoreConsumption,
];

export const FIELD_ID_MAP: Record<string, string> = {
	durationMin: METRIC_DEFINITION_IDS.durationMin,
	totalDistanceM: METRIC_DEFINITION_IDS.totalDistanceM,
	totalDistanceMPerMin: METRIC_DEFINITION_IDS.totalDistancePerMin,
	maxSpeedKMH: METRIC_DEFINITION_IDS.maxSpeedKMH,
	highIntensityM: METRIC_DEFINITION_IDS.highIntensityM,
	highIntensityRate: METRIC_DEFINITION_IDS.highIntensityRate,
	noOfSprint: METRIC_DEFINITION_IDS.noOfSprint,
	sprintDistanceM: METRIC_DEFINITION_IDS.sprintDistanceM,
	speedZone1DistanceM: METRIC_DEFINITION_IDS.speedZone1DistanceM,
	speedZone6DistanceM: METRIC_DEFINITION_IDS.speedZone6DistanceM,
	speedZone7DistanceM: METRIC_DEFINITION_IDS.speedZone7DistanceM,
	speedZone8DistanceM: METRIC_DEFINITION_IDS.speedZone8DistanceM,
	speedZone9DistanceM: METRIC_DEFINITION_IDS.speedZone9DistanceM,
	lowIntensityRate: METRIC_DEFINITION_IDS.lowIntensityRate,
	accelerationZone5EntryCount: METRIC_DEFINITION_IDS.accelerationZone5EntryCount,
	accelerationZone6EntryCount: METRIC_DEFINITION_IDS.accelerationZone6EntryCount,
	accelerationCountTotal: METRIC_DEFINITION_IDS.accelerationCountTotal,
	noOfExpAcc: METRIC_DEFINITION_IDS.noOfExpAcc,
	decelerationZone5EntryCount: METRIC_DEFINITION_IDS.decelerationZone5EntryCount,
	decelerationZone6EntryCount: METRIC_DEFINITION_IDS.decelerationZone6EntryCount,
	decelerationCountTotal: METRIC_DEFINITION_IDS.decelerationCountTotal,
	noOfExpDec: METRIC_DEFINITION_IDS.noOfExpDec,
	noOfHSR: METRIC_DEFINITION_IDS.noOfHSR,
	HSRDistanceM: METRIC_DEFINITION_IDS.hsrDistanceM,
	trainingScoreConsumption: METRIC_DEFINITION_IDS.trainingScoreConsumption,
};
