export const trainigMetricDefinitionIds = [
	'KkLOxGTCHY2uVOMjLtQE',
	'P6Zu5epLjDOaDQq20Stx',
	'I7i8bessV96ciVnFw5IB',
	'Q4dPRJ2eqeNR0Bg4DI3E',
	'Kn39OEkrpQCMQAtMQb5J',
	'RObqK0yOMf4NXhiWig6p',
	'ZfqkRYcNfvwYioquCx5h',
	'mVykVPzBokSZ0l4C7YhJ',
	'0xbH1n71xspfVRddG92Q',
	'oOQMjHICxmf3nLwvDitk',
	'kCZxKxfA9MfWVgBmdTbo',
	'YR3ZEOZLTLwJk23XKVpj',
	'XYpyu5CZTDZmMY9DbfNG',
	'XLp9zGyDi0PgkNHn61ln',
	'g60b48TuNLrtstb0dy65',
	'mPoLSRIgbc1IwC3fPsP9',
	'D7aoPeenTMYu3CxfR6v7',
	'vMV5RRPagpuPxkoU8F2T',
	'b3DroV7arY2KLRUJpdtq',
];

export const FIELD_ID_MAP: Record<string, string> = {
	durationMin: 'KkLOxGTCHY2uVOMjLtQE',
	totalDistanceM: 'P6Zu5epLjDOaDQq20Stx',
	totalDistanceMPerMin: 'I7i8bessV96ciVnFw5IB',
	maxSpeedKMH: 'Q4dPRJ2eqeNR0Bg4DI3E',
	highIntensityM: 'Kn39OEkrpQCMQAtMQb5J',
	highIntensityRate: 'RObqK0yOMf4NXhiWig6p',
	noOfSprint: 'ZfqkRYcNfvwYioquCx5h',
	sprintDistanceM: 'mVykVPzBokSZ0l4C7YhJ',
	speedZone1DistanceM: '0xbH1n71xspfVRddG92Q',
	walkingRate: 'oOQMjHICxmf3nLwvDitk',
	accelerationZone5EntryCount: 'kCZxKxfA9MfWVgBmdTbo',
	accelerationZone6EntryCount: 'YR3ZEOZLTLwJk23XKVpj',
	accelerationCountTotal: 'XYpyu5CZTDZmMY9DbfNG',
	noOfExpAcc: 'XLp9zGyDi0PgkNHn61ln',
	decelerationZone5EntryCount: 'g60b48TuNLrtstb0dy65',
	decelerationZone6EntryCount: 'mPoLSRIgbc1IwC3fPsP9',
	decelerationCountTotal: 'D7aoPeenTMYu3CxfR6v7',
	noOfExpDec: 'vMV5RRPagpuPxkoU8F2T',
	trainingScoreConsumption: 'b3DroV7arY2KLRUJpdtq',
};
