mutation CreatePerformanceAssessmentParticipant($data: PerformanceAssessmentParticipantCreate!) {
	createPerformanceAssessmentParticipant(data: $data) {
		id
		email
		number
		fullName
		orgUniqueToken
	}
}
