query ListPersons($orgId: ID!) {
	listPersons(data: { conditions: { orgId: $orgId }, pageOption: { size: 1000 } }) {
		# ...PersonsInPersonsList
		records {
			id
			fullName
			birthday
			isAnonymous
			kana
			sex
			externalId
			orgUniqueToken
		}
	}
}
